### ISSUE TITLE
PHPUnit 10 withConsecutive

### ISSUE THREAD

**Issue by erickskrauch** [Yoast/PHPUnit-Polyfills#144]
Hello.

In PHPUnit 10 method `withConsecutive` has been removed. [There is](https://gist.github.com/oleg-andreyev/85c74dbf022237b03825c7e9f4439303) a suggested workaround.

Since this library tends to polyfill remove functionality, it will be nice to have a polyfill for that method in this library.

**Comment by jrfnl** [comment]
@erickskrauch I think you misunderstand this library. This library makes the tests _forward_ compatible - i.e. it polyfills _new_ PHPUnit functionality -, not _backward_ compatible.

In practice, _forward_ compatible means you can write your tests for the latest PHPUnit version (= use all the assertions/expectations available in the latest PHPUnit version) and this library will make sure your tests will run without problems on older PHPUnit versions.

This allows you to keep your test suite up to date with the latest PHPUnit, and the choice for whether and when to upgrade is yours.

_Backward_ compatible means you would never upgrade your test code unless forced at knife point by a PHP version which just won't run your tests anymore on ancient PHPUnit versions and that is exactly the scenario this library allows you to _avoid_.

So, no, polyfilling `withConsecutive` is out of scope for this package.

**Comment by erickskrauch** [comment]
@jrfnl, thank you for the detailed explanation.

I just thought that this is the case for this library since there is a polyfill for removed [`assertAttribute*()` methods](https://github.com/Yoast/PHPUnit-Polyfills#helper-traits). Also removed functionality, also need to allow perform the same tests across multiple PHPUnit versions.

But I guess it's something else.

**Comment by jrfnl** [comment]
@erickskrauch Ah, I see what you mean now. Okay, so that's a "helper", not a polyfill. Helpers are intended to buy people some time for changes which can't be worked round easily and would likely need a change in the "code under test" to allow the functionality to still be tested like before.

To work around `withConsecutive` changing the code under test would never be needed, it would be a test-only change, which is why I don't think it qualifies.

Also note: as a general rule of thumb, helpers are only around for one or two majors of the PHPUnit Polyfills as they are there to buy time, not to "undo" the PHPUnit change.
